feat: improve key creation/import options when creating identifiers
decentralized-identity/veramo pull request #1423
Opened 2024-10-28 20:05 UTC by 0x62

## RFC

This PR is a draft, at the moment no unit/integration tests have been added. If there is appetite to merge this change I will add tests.

## What issue is this PR fixing

At the moment, specifying key options when creating identifiers (via `didManagerCreate`) is fragile. Each provider has a slightly different format for `options`, and many omit the ability to provide `meta` for keys. This is a problem, as it means there is no nice way to create both an identifier and associated keys if you need to store metadata.

This PR proposes some non-breaking changes to each of the DID providers that unifies key option signature, adds support for key metadata and privateKeyHex to a couple of the providers which didn't support that. 

All KMS key options are now unified under `options.key` (or `options.agreementKey` and `options.authKey` for `did:peer`).

If no `options.key` is provided, each provider falls back to the currently support confirmation signature.

## What is being changed

`createIdentifier` now has a reasonably unified signature for passing key options like `privateKeyHex` and `meta` for each of the providers:

```
interface CreateDidExampleOptions {
  /**
   * Non-key related options at root level, e.g
   */
  namespace: string;
  chainId?: string | number;

  /**
   * Options passed to KMS when creating/importing
   */
  key?: {
    type?: TKeyType; // sometimes - depends on whether applies to provider
    privateKeyHex?: string;
    meta?: KeyMetadata;
  }
}
```

For `did:peer`, there are both `agreementKey` and `authKey` options instead of a single `key`. 

### did-provider-ethr

- Adds the option to import a key through `options.key.privateKeyHex`
- Adds the option to specify key metadata through `options.key.meta`

### did-provider-ion

No changes, this provider already supports passing key metadata under `options.key`. 

### did-provider-jwk

- DEPRECATED: `options.keyType` deprecated in favour of `options.key.type`
- DEPRECATED: `options.privateKeyHex` deprecated in favour of `options.key.privateKeyHex`
- Adds the option to specify key metadata through `options.key.meta`

### did-provider-key

- DEPRECATED: `options.keyType` deprecated in favour of `options.key.type`
- DEPRECATED: `options.privateKeyHex` deprecated in favour of `options.key.privateKeyHex`
- Adds the option to specify key metadata through `options.key.meta`

### did-provider-peer

- DEPRECATED: `options.authPrivateKeyHex` deprecated in favour of `options.authKey.privateKeyHex`
- DEPRECATED: `options.agreementPrivateKeyHex` deprecated in favour of `options.agreementKey.privateKeyHex`
- Adds the option to specify auth key metadata through `options.authKey.meta`
- Adds the option to specify agreement key metadata through `options.agreementKey.meta`

### did-provider-pkh

- DEPRECATED: `options.privateKey` deprecated in favour of `options.key.privateKeyHex`
- Adds the option to specify key metadata through `options.key.meta`

### did-provider-web

- DEPRECATED: `options.keyType` deprecated in favour of `options.key.type`
- Adds the option to specify private key through `options.key.privateKeyHex`
- Adds the option to specify key meta through `options.key.meta`

## Quality
Check all that apply:
* [X] I want these changes to be integrated
* [X] I successfully ran `pnpm i`, `pnpm build`, `pnpm test`, `pnpm test:browser` locally.
* [X] I allow my PR to be updated by the reviewers (to speed up the review process).
* [ ] I added unit tests.
* [ ] I added integration tests.
* [X] I did not add automated tests because I'm waiting for confirmation there is appetite from maintainers to merge, and I am aware that a PR without tests will likely get rejected.

2024-10-28 21:36 UTC, mirceanis reviewed
Yes, there is definitely appetite for including this kind of work. 
Thank you for proposing this!!

--

* try to reduce code duplication, like for importOrGenerateKey
* What do you think about authKey being just key for did:peer? It would allow a simpler options type to be extended by all did providers 
* specifying just the kid would be a simpler API, even when requiring 2 calls to create a DID from a predefined key, but it would be a breaking change.

2024-10-30 11:28 UTC, mirceanis commented
> I'd be in favour of keeping the option to do both. As currently implemented, it is non-breaking. I did consider a signature like `key: { kid: string; }`, but this also has ambiguity in whether you're looking up a key by KID or providing a KID for the key being created. `keyRef` has precedent in Veramo (e.g `keyManagerSign({ keyRef: 'xyz' })`), as opposed to a new signature

Agreed. Naming the internal property `kid` was a mistake as it's usually a public JWT header property confusing everyone.
We tried to migrate to `keyRef` at some point but not all the way through. I suppose a simple `id` property would have been better.. or `alias` would have worked as well.

Suggestions welcome!

2024-10-30 12:11 UTC, mirceanis requested changes
Generally looks good.

There are some typos to be fixed for did:peer:2 and I think some workspace dependencies need to be referenced in their corresponding tsconfig files.

2024-10-30 12:11 UTC, mirceanis commented on packages/did-provider-ethr/package.json
> +    "@veramo/utils": "workspace:^",
I think we should also have a reference in the `did-provider-ethr/tsconfig.json` for this workspace package

2024-10-30 12:11 UTC, mirceanis commented on packages/did-provider-pkh/package.json
> +    "@veramo/utils": "workspace:^",
I think we should also have a reference in the `did-provider-pkh/tsconfig.json` for the utils package

2024-10-30 12:11 UTC, mirceanis commented on packages/did-provider-web/package.json
> +    "@veramo/utils": "workspace:^",
I think we should also have a reference in the `did-provider-web/tsconfig.json` for this workspace package

2024-10-30 16:06 UTC, 0x62 commented
Thanks for the review @mirceanis, should all be fixed

2024-10-31 09:55 UTC, mirceanis approved these changes
Looks great, thank you for the contribution!

2024-10-31 10:01 UTC, merged